SCALE = 2

PIXEL_WIDTH = 400
PIXEL_HEIGHT = 300

WINDOW_WIDTH  = PIXEL_WIDTH * SCALE
WINDOW_HEIGHT = PIXEL_HEIGHT * SCALE

FONT_SIZE = 14
LINE_HEIGHT = FONT_SIZE + 2
FONT_NAME = "MonospaceTypewriter.ttf"

CONSOLE_LINES = 5
CONSOLE_MARGIN = 4

LURK_LAG = 1