WINDOW_WIDTH  = 800
WINDOW_HEIGHT = 500

SCALE = 4

PIXEL_WIDTH = WINDOW_WIDTH / SCALE
PIXEL_HEIGHT = WINDOW_HEIGHT / SCALE

FONT_SIZE = 14
LINE_HEIGHT = FONT_SIZE + 2
FONT_NAME = "MonospaceTypewriter.ttf"

CONSOLE_LINES = 5
CONSOLE_MARGIN = 4

LURK_LAG = 1