SCALE = 4

PIXEL_WIDTH = 320
PIXEL_HEIGHT = 200

WINDOW_WIDTH  = PIXEL_WIDTH * SCALE
WINDOW_HEIGHT = PIXEL_HEIGHT * SCALE

FONT_SIZE = 14
LINE_HEIGHT = FONT_SIZE + 2
FONT_NAME = "MonospaceTypewriter.ttf"

CONSOLE_LINES = 5
CONSOLE_MARGIN = 4

LURK_LAG = 1

function displayCoord(y)
  return PIXEL_HEIGHT - y
end